# Generated by Django 3.2.9 on 2021-12-13 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_auto_20211212_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_num', models.CharField(max_length=7, unique=True, verbose_name='图书编号')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('remarks', models.CharField(blank=True, max_length=32, null=True, verbose_name='简介')),
                ('status', models.IntegerField(max_length=1, verbose_name='图书状态')),
            ],
        ),
        migrations.CreateModel(
            name='returninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookuser', models.CharField(max_length=32, verbose_name='借阅人')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('time_begin', models.DateField(auto_now=True, null=True, verbose_name='借阅开始时间')),
                ('time_end', models.DateField(auto_now=True, null=True, verbose_name='借阅结束时间')),
                ('approve_date', models.DateField(auto_now=True, null=True, verbose_name='登记时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='头像')),
                ('user_obj', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='borrowinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookuser', models.CharField(max_length=32, verbose_name='借阅人')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('time_begin', models.DateField(auto_now=True, null=True, verbose_name='借阅开始时间')),
                ('time_end', models.DateField(auto_now=True, null=True, verbose_name='借阅结束时间')),
                ('approve_date', models.DateField(auto_now=True, null=True, verbose_name='审批时间')),
                ('approve_status', models.CharField(blank=True, choices=[('0', '未审批'), ('1', '通过审批')], max_length=1, null=True, verbose_name='审批状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.bookinfo')),
            ],
        ),
    ]
