# Generated by Django 3.2.9 on 2021-12-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_borrowinfo_oprator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '未借出'), ('1', '已借出')], max_length=1, null=True, verbose_name='图书状态'),
        ),
    ]
